title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://happy-dune-08b55a500.4.azurestaticapps.net/

aux_links:
  Template Repository: https://github.com/hojunking/vienna_sausages_archive
